name: LTSpawn
main: cn.ltcraft.spawn.LTSpawn
version: 0.0.1
softdepend:
  - "HolographicDisplays"
commands:
  lts:
    description: 刷怪点管理
    usage: /lts args...
    permission: LTSpawn.lts
permissions:
  LTSpawn.lts:
    description: 刷怪点管理
    default: op